language: python
python: 2.7
env:
  global:
    - COVERALLS_CMD=true
  matrix:
    - TOXENV=py34
    - TOXENV=py33
    - TOXENV=py27
    - TOXENV=py26
    - COVERALLS_DEP=coveralls
      COVERALLS_CMD=coveralls
      COVERAGE_DEP=coverage
      COVERAGE_CMD="coverage run --append --source=facebookads"
install:
  - pip install tox $COVERALLS_DEP
script:
  - tox
after_script:
  - $COVERALLS_CMD
